apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    url: http://hackathon_prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    url: http://hackathon_loki:3100
    access: proxy
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id\":\"([a-f0-9]+)\""
          name: TraceID
          url: "${__value.raw}"
          urlDisplayLabel: "View Trace in Tempo"

  - name: Tempo
    type: tempo
    uid: tempo
    orgId: 1
    url: http://hackathon_tempo:3200
    access: proxy
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        filterByTraceID: true
      nodeGraph:
        enabled: true
